GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic2FtIiwiaWF0IjoxNjQ4NTE0Mzg0LCJleHAiOjE2NDg1MTQ0MTR9.tToWH_0JVH0BUEVxEzjm9MfPh4_h-71uwusiblOlAVk

###

POST http://localhost:4000/
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic2FtIiwiaWF0IjoxNjQ4NTE0MzUwfQ.AJXGjK9SzjzRJ8NtUa8qHJ79c-mkwhyUHNN7ZdZnG5g"
}

###  

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "sam"
}